server:
  port: 4006

spring:
  application:
    name: livegoods-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: livegoods-banner
          uri: lb://livegoods-banner
          predicates:
            - Path=/banner/**
        - id: livegoods-hot-product
          uri: lb://livegoods-hot-product
          predicates:
            - Path=/hotProduct/**
            - Query=city
        - id: livegoods-recommendation
          uri: lb://livegoods-recommendation
          predicates:
            - Path=/recommendation/**
            - Query=city
        - id: livegoods-search
          uri: lb://livegoods-search
          predicates:
            - Path=/search/**
            - Query=city
            - Query=content
            - Query=page
        - id: livegoods-product-details
          uri: lb://livegoods-product-details
          predicates:
            - Path=/details/**
            - Query=id
        - id: livegoods-comment
          uri: lb://livegoods-comment
          predicates:
            - Path=/comment/**
            - Query=id

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:
      defaultZone: http://192.168.56.101:8761/eureka/