server:
  port: 7010

spring:
  application:
    name: livegoods-search
  profiles:
    active: mongodb,commons
  elseticsearch:
    rest:
      urls: http://192.168.57.3:9200

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.56.101:8761/eureka/